# -*- coding: utf-8 -*-
"""BERT + PyTorch Topological.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ee1VmtlXN1MYRya8jkiOX9RDvNyXu3x
"""


import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

import transformers

import torch_topological
#print(torch_topological.__version__)
from torch_topological.nn import WassersteinDistance
from torch_topological.nn import SummaryStatisticLoss



"""Load Data"""

import pandas as pd
import numpy as np
# from datasets import load_dataset

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TuringBench_Data

train = pd.read_csv("synscipass_dataset_train.csv", encoding="latin-1")
test = pd.read_csv("synscipass_dataset_test.csv", encoding="latin-1")
valid = pd.read_csv("synscipass_dataset_validation.csv", encoding="latin-1")

#train['label'].unique()

def change_label(data):
  new_label = []
  for i in data['model']:
    
    if i == 'real':
      new_label.append(0)
    elif i == 'gpt2-medium':
      new_label.append(1)
    elif i == 'distilgpt2':
      new_label.append(2)
    elif i == 'scigen':
      new_label.append(3)
    elif i == 'opus-es-en':
      new_label.append(4)
    elif i == 'google_translate':
      new_label.append(5)
    elif i == 'pegasus-xsum-finetuned-paws-parasci':
      new_label.append(6)
    elif i == 'GPT-2-arxiv_generate':
      new_label.append(7)
    elif i == 'opus-es-en-scielo':
      new_label.append(8)
    elif i == 'pegasus-xsum-finetuned-paws':
      new_label.append(9)
    elif i == 'bloom':
      new_label.append(10)
    elif i == 'spinbot':
      new_label.append(11)
#    else:
#      new_label.append(19)

  return pd.DataFrame({'text': data['passages'], 'label': new_label})


train = change_label(train)
test = change_label(test)
valid = change_label(valid)


def trim_data(data):
  one = data[data['label'] == 1]
  two = data[data['label'] == 2]
  three = data[data['label'] == 3]
  four = data[data['label'] == 0]
  
  return pd.concat([one, two, three, four])

#train = trim_data(train)
#test = trim_data(test)
#valid = trim_data(valid)


#print("unique labels: ", train['label'].unique())

"""Classifier"""

# Commented out IPython magic to ensure Python compatibility.
import transformers
from transformers import BertModel, BertTokenizer, AdamW, get_linear_schedule_with_warmup 
from transformers import RobertaTokenizer, RobertaModel
import torch
import numpy as np
import pandas as pd
import seaborn as sns
# from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from collections import defaultdict
from textwrap import wrap
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from transformers import BertModel, BertTokenizer#, AdamW, get_linear_schedule_with_warmup
from transformers import AutoTokenizer, AutoModel
import transformers

RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")



"""Data Processing"""

from transformers import AutoTokenizer, AutoModelForMaskedLM
PRE_TRAINED_MODEL_NAME = 'roberta-base'
tokenizer = RobertaTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME)
MAX_LEN = 512 #400

"""Data Loader"""

class Text_Generation(Dataset):
  
  def __init__(self, text, label, tokenizer, max_len):
    self.text = text
    self.label = label
    self.tokenizer = tokenizer
    self.max_len = max_len
  
  def __len__(self):
    return len(self.text)
  
  def __getitem__(self, item):
    review = str(self.text[item])
    target = self.label[item]
    encoding = self.tokenizer.encode_plus(
      review,
      add_special_tokens=True,
      max_length=self.max_len,
      return_token_type_ids=False,
      pad_to_max_length=True,
      return_attention_mask=True,
      return_tensors='pt',
    )
    
    return {
      'text': review,
      'input_ids': encoding['input_ids'].flatten(),
      'attention_mask': encoding['attention_mask'].flatten(),
      'label': torch.tensor(target, dtype=torch.long)
    }

train.shape, valid.shape, test.shape

def create_data_loader(df, tokenizer, max_len, batch_size):
  
  ds = Text_Generation(
    text=df.text.to_numpy(),
    label=df.label.to_numpy(),
    tokenizer=tokenizer,
    max_len=max_len
  )

  return DataLoader(ds, batch_size=batch_size, num_workers=4, shuffle=True)

BATCH_SIZE = 16 #4 #16

train_data_loader = create_data_loader(train, tokenizer, MAX_LEN, BATCH_SIZE)
val_data_loader = create_data_loader(valid, tokenizer, MAX_LEN, BATCH_SIZE)
test_data_loader = create_data_loader(test, tokenizer, MAX_LEN, BATCH_SIZE)

#train_data_loader.dataset.text[1]

"""BERT Classifier"""

#bert_model = BertModel.from_pretrained(PRE_TRAINED_MODEL_NAME)

from sklearn.decomposition import PCA
import seaborn as sns
from sklearn.preprocessing import scale, normalize

from torch_topological.datasets import SphereVsTorus
from torch_topological.nn.data import make_tensor, make_tensor_from_persistence_information
from torch_topological.nn import VietorisRipsComplex
from torch_topological.nn.layers import StructureElementLayer
from torch.utils.data import DataLoader
from tqdm import tqdm
import torch


class GeneratorClassifier(nn.Module):
  
  def __init__(self, n_classes):
    super(GeneratorClassifier, self).__init__()
    self.bert =  RobertaModel.from_pretrained(PRE_TRAINED_MODEL_NAME, return_dict=False)
    self.drop = nn.Dropout(p=0.3)
    
    self.tda_vr = VietorisRipsComplex(dim=0)
    self.tda_out = nn.Linear(2301, n_classes)
  
  def forward(self, input_ids, attention_mask):
    _, pooled_output, attentions, output_hidden_states = self.bert(
      input_ids=input_ids,
      attention_mask=attention_mask,
      output_attentions=True,
      output_hidden_states=True
    )

  
    output = self.drop(pooled_output)

    #print("attentions: ", attentions[0])
    #print("attentions size: ", attentions[0].size())
    
    final_pers_info = []
    for i, x in enumerate(attentions[0]):
      pers_info = self.tda_vr(x)
      pers_info = make_tensor(pers_info)

      pers = torch.flatten(pers_info)
      final_pers_info.append(pers)


    finals = []
    for i in final_pers_info:
      if len(i) == 1533:
        finals.append(i)
      if len(i) < 1533:
        new = torch.cat((i, torch.zeros(1533 - len(i), device='cuda'))).to(device)
        new = torch.flatten(new)
        finals.append(new)
    
    final_pers_info = torch.stack(finals, dim=1).to(device) 
    tda_output = torch.transpose(final_pers_info, 0, 1)
    combined_output = self.tda_out(torch.cat((output, tda_output), dim=1))
    
    return combined_output 

model = GeneratorClassifier(len(train['label'].unique())) 
model = model.to(device)

EPOCHS = 5 #20 #10
optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
total_steps = len(train_data_loader) * EPOCHS



scheduler = get_linear_schedule_with_warmup(
  optimizer,
  num_warmup_steps=0,
  num_training_steps=total_steps
)

loss_fn = nn.CrossEntropyLoss().to(device)


def train_epoch(model, data_loader, loss_fn, optimizer, device, scheduler, n_examples):

  model = model.train()
  losses = []
  correct_predictions = 0
  for d in data_loader:
    input_ids = d["input_ids"].to(device)
    attention_mask = d["attention_mask"].to(device)
    label = d["label"].to(device)
    print("label: ", label)

    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
    #print("outputs: ", outputs)
    
    _, preds = torch.max(outputs, dim=1)
    print("preds: ", preds)

    loss = loss_fn(outputs, label)
    print("loss: ", loss)
    
    correct_predictions += torch.sum(preds == label)
    losses.append(loss.item())
    loss.backward()
    nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()
    scheduler.step()
    optimizer.zero_grad()
    
  return correct_predictions.double() / n_examples, np.mean(losses)

def eval_model(model, data_loader, loss_fn, device, n_examples):
  model = model.eval()
  losses = []
  correct_predictions = 0
  with torch.no_grad():
    for d in data_loader:
      input_ids = d["input_ids"].to(device)
      attention_mask = d["attention_mask"].to(device)
      label = d["label"].to(device)

      outputs = model(input_ids=input_ids, attention_mask=attention_mask)
      
      _, preds = torch.max(outputs, dim=1)
      
      loss = loss_fn(outputs, label)
      
      correct_predictions += torch.sum(preds == label)
      losses.append(loss.item())
    
  return correct_predictions.double() / n_examples, np.mean(losses)

# %%time

history = defaultdict(list)
best_accuracy = 0

progress = tqdm(range(EPOCHS))

for epoch in progress:
  print(f'Epoch {epoch + 1}/{EPOCHS}')
  print('-' * 10)
  
  train_acc, train_loss = train_epoch(model, train_data_loader, loss_fn, optimizer, device, scheduler, len(train))
  print(f'Train loss {train_loss} accuracy {train_acc}')
  
  val_acc, val_loss = eval_model(model, val_data_loader, loss_fn, device, len(valid))
  print(f'Val loss {val_loss} accuracy {val_acc}')
  print()
  
  history['train_acc'].append(train_acc)
  history['train_loss'].append(train_loss)
  history['val_acc'].append(val_acc)
  history['val_loss'].append(val_loss)
  
  if val_acc > best_accuracy:
    torch.save(model.state_dict(), 'roberta_tda_attentions_scigen.bin')
    best_accuracy = val_acc




test_acc, _ = eval_model(
  model,
  test_data_loader,
  loss_fn,
  device,
  len(test)
)


test_acc.item()

def get_predictions(model, data_loader):
  model = model.eval()
  review_texts = []
  predictions = []
  prediction_probs = []
  real_values = []
  
  with torch.no_grad():
    for d in data_loader:
      texts = d["text"]
      input_ids = d["input_ids"].to(device)
      attention_mask = d["attention_mask"].to(device)
      targets = d["label"].to(device)
      
      outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
      )

      _, preds = torch.max(outputs, dim=1)
      review_texts.extend(texts)
      predictions.extend(preds)
      prediction_probs.extend(outputs)
      real_values.extend(targets)

  predictions = torch.stack(predictions).cpu()
  prediction_probs = torch.stack(prediction_probs).cpu()
  real_values = torch.stack(real_values).cpu()

  return review_texts, predictions, prediction_probs, real_values

y_review_texts, y_pred, y_pred_probs, y_test = get_predictions(
  model,
  test_data_loader
)

class_names = ['real', 'gpt2-medium', 'distilgpt2', 'scigen', 'opus-es-en',
               'google_translate', 'pegasus-xsum-finetuned-paws-parasci',
               'GPT-2-arxiv_generate', 'opus-es-en-scielo',
               'pegasus-xsum-finetuned-paws', 'bloom', 'spinbot']

print(classification_report(y_test, y_pred, target_names=class_names, digits=4))

def show_confusion_matrix(confusion_matrix):
  hmap = sns.heatmap(confusion_matrix, annot=True, fmt="d", cmap="Blues")
  hmap.yaxis.set_ticklabels(hmap.yaxis.get_ticklabels(), rotation=0, ha='right')
  hmap.xaxis.set_ticklabels(hmap.xaxis.get_ticklabels(), rotation=70, ha='right')
  
  plt.ylabel('True Label')
  plt.xlabel('Predicted Label')
  plt.savefig("/home/azu5030/tda_proj/" + "roberta_tda_attentions_scigen_confusion_matrix.png");
  
cm = confusion_matrix(y_test, y_pred)
df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)
show_confusion_matrix(df_cm)

